### ISSUE TITLE
They do provide a Win32 API for getting string length

### ISSUE THREAD

**Issue by CarterLi** [neosmart/paste#1]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms647492(v=vs.85).aspx
Simple loop is used if you look into its implementation😆 
Also prefix those strings with `L` so that we don't need write a function template

**Comment by mqudsi** [comment]
I didn't know about the WIN32 `lstrlen` function, thank you.

The project is configured as multi-byte characters so we can use standard C/C++ APIs without the TCHAR/Unicode mess, but the WIN32 API for getting the contents of the clipboard as unicode returns UTF16, not UTF8.. but that's why there's that split between `wchar_t` and `char`. Let me see if I can just use wide strings for console output.

**Comment by CarterLi** [comment]
I was saying `lstrlenW`.
True console, aka conhost, doesn't play well with UTF-8. Characters will be converted into system's local encoding ( aka code page, CP936 for me ) before printing. Writing UTF-8 as narrow (multi-byte) characters won't work.
It's 2017. There's no reason using the ANSI version if the UNICODE version exists.

**Comment by mqudsi** [comment]
It's not ANSI actually, it's UTF-8. You can interface with the C++11/C++17 standard library and use `std::string` or `char` for unicode (not "Unicode" aka UTF-16 or the legacy UCS-2) to get cross-platform, multilanguage support. The VC++ project is configured as MBCS (multi-byte character set), not ANSI.

To clarify, this is in reference to your last sentence. Not disagreeing with anything else you said above that. To get UTF-8 to output correctly to the console, the console's codepage must first be changed. And conhost's codepage support is miserable.

**Comment by CarterLi** [comment]
> It's not ANSI actually, it's UTF-8.

Yes, for *nix; no, for Windows.
[The encoding of narrow multibyte string literals is implementation-defined](http://en.cppreference.com/w/cpp/language/string_literal), [not necessarily UTF-8](http://en.cppreference.com/w/cpp/string/multibyte). For Windows, they will be converted into system's local encoding, when compiling, but UTF-8, even the source code itself is encoded in UTF-8. UTF-[8|16|32] strings [have their own syntax](http://en.cppreference.com/w/cpp/language/string_literal).
There's nothing matters for ASCII only strings, since ASCII strings are also UTF-8 strings. But it does matter for non-English system users.
PS: The encoding of wide strings are also implementation-defined, for Windows it's UTF-16 ( nowadays, like you said ); for *nix, it's UTF-32. 
PS2: [UTF-8](https://en.wikipedia.org/wiki/UTF-8) means 8-bit **Unicode** Transformation Format

**Comment by CarterLi** [comment]
> Characters will be converted into system's local encoding ( aka code page, CP936 for me ) before printing.

Clarification: For Windows, narrow strings are converted to wide strings for low-level operations; And are converted back to narrow strings ( by conhost? don't know ) for printing.

**Comment by mqudsi** [comment]
Just to clarify, I'm aware of that UTF-8/16/32, etc. are all different encodings of the Unicode range. The real question is about the behavior of MBCS under VC++ and how that affects the internal implementation of system calls and the encoding of `std::string` (if it affects it in any way).

While defining `_UNICODE`, the xxxW version of the system functions are called, but when `_MBCS` is defined, the xxxA version is still called, just like it would be without `_MBCS`. 

This is what MS says about MBCS:

> Support for a form of multibyte character set (MBCS) called double-byte character set (DBCS) on all platforms.
> DBCS characters are composed of 1 or 2 bytes. Some ranges of bytes are set aside for use as lead bytes. A lead byte specifies that it and the following trail byte comprise a single 2-byte-wide character. You must keep track of which bytes are lead bytes. In a particular multibyte-character set, the lead bytes fall within a certain range, as do the trail bytes. When these ranges overlap, it might be necessary to evaluate the context to determine whether a given byte is functioning as a lead byte or a trail byte.

That definition fits utf-8 very well, and yet, I'm not able to devise a test case off the top of my head that shows that `_MBCS` actually affects anything in any way. It seems to be treated the same way as regular, ANSI code.

That's not what I had expected. Just going by MS' definition of MBCS/DBCS, the expectation was that it would affect the behavior of internal encoding of _something_, not interpret it as ANSI and just go with it... so does that mean cross-platform C++ code that _isn't_ `#ifdef'd` everywhere (or `typedef` or whatever) can't be Unicode-ready on all platforms and conversion will always be needed before sending data anywhere the user can see it?

**Comment by CarterLi** [comment]
> While defining _UNICODE, the xxxW version of the system functions are called, but when _MBCS is defined, the xxxA version is still called, just like it would be without _MBCS.

For most Win32 API, yes. Use it together with `_T`.

> That definition fits utf-8 very well, and yet, I'm not able to devise a test case off the top of my head that shows that _MBCS actually affects anything in any way.

Simple test case:
![image](https://cloud.githubusercontent.com/assets/6134068/24328336/83c5ceec-1219-11e7-8c45-9f451d12d5bd.png)
I used the word **你好** from http://en.cppreference.com/w/cpp/string/multibyte. As you can see, the default encoding of narrow strings and utf-8 strings are different on Windows ( I'm using VS2017 ). Narrow string of **你好** is encoded to 4 bytes (CP936, aka GBK) and UTF-8 string of **你好** is 6 bytes, as it reads in cppreference.

**Comment by mqudsi** [comment]
Isn't that C++11's `u8` support being demoed and not `_MBCS`? I understand how `u8` or `u` or `U` change things from a C++ aspect, the question is how the interaction between these and native Windows APIs differs based on the presence or absence of `_MBCS`.

**Comment by mqudsi** [comment]
e.g. this code sample creates a utf8-encoded filename correctly under Linux, but not under Windows.. regardless of whether `_MBCS` is defined or not, regardless of whether the standard C++ api is used or the Windows API:

	#include "stdafx.h"
	#include <string>
	#include <iostream>
	#include <ostream>

	template < typename T, size_t N >
	size_t _countof( T ( & arr )[ N ] )
	{
		return std::extent< T[ N ] >::value;
	}

	int strlen_u8(const char *s)
	{
		int len = 0;
		while (*s) len += (*s++ & 0xc0) != 0x80;

		return len;
	}

	int main()
	{
	#ifdef _WIN32
		SetConsoleOutputCP(65001); //utf-8
	#endif

		//this is explicitly, undeniably UTF-8. We're using raw bytes, so no chance of internal encoding differences
		uint8_t rawBytes[] = { 0xD8, 0xA3, 0xD9, 0x86, 0xD8, 0xA7, 0x20, 0xD9, 0x82, 0xD8, 0xA7, 0xD8, 0xAF, 0xD8, 0xB1, 0x20, 0xD8, 0xB9, 0xD9, 0x84, 0xD9, 0x89, 0x20, 0xD8, 0xA3, 0xD9, 0x83, 0xD9, 0x84, 0x20, 0xD8, 0xA7, 0xD9, 0x84, 0xD8, 0xB2, 0xD8, 0xAC, 0xD8, 0xA7, 0xD8, 0xAC, 0x20, 0xD9, 0x88, 0x20, 0xD9, 0x87, 0xD8, 0xB0, 0xD8, 0xA7, 0x20, 0xD9, 0x84, 0xD8, 0xA7, 0x20, 0xD9, 0x8A, 0xD8, 0xA4, 0xD9, 0x84, 0xD9, 0x85, 0xD9, 0x86, 0xD9, 0x8A, 0x2E, 0x00 };
		std::string testData = (const char *)(rawBytes);

		//for Windows only
	#ifdef _WIN32
		CreateFile(testData.c_str(), GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
	#endif
		std::fopen(testData.c_str(), "w");

		std::cout << "bytes:  " << _countof(rawBytes) - 1 << std::endl;
		std::cout << "strlen: " << strlen_u8(testData.c_str()) << std::endl;

	    return 0;
	}

**Comment by CarterLi** [comment]
Win32 API can't handle UTF-8 strings.
All narrow strings are converted internally to wide strings using [MultiByteToWideChar](https://msdn.microsoft.com/zh-cn/library/windows/desktop/dd319072(v=vs.85).aspx). When converting, how to determine which encoding is used by the string? (Note: their types are both `const char *`). They can't. As a result, the default code page of current system language (`CP_ACP`) are used, since all narrow strings are supposed to be encoded in system default code page by the compiler.
In a word: They will treat UTF-8 strings as narrow strings.

**Comment by mqudsi** [comment]
Yeah, unfortunately.

I was not planning on doing anything about `lstrlen` since our existing solution works and there's nothing to be gained by the switch. However, the fact that there's no benefit to mixing "mbcs" and UTF-16 strings in the same application and that it was being treated as ANSI anyway convinced me to switch it all to wide strings and call `lstrlen` instead of the home-baked `strlen` function.

**Comment by CarterLi** [comment]
Using the general name `lstrlen` doesn't make sense in this case.
The general name of Win32 APIs are defined for easy migration. Since you use wide strings everywhere, simply change the project to MBCS won't work.
In order to use `lstrlen` & others, you must use `_T` ( an ugly macro defined in `tchar.h` to encode string dynamically), use general char type `TCHAR`, use general string type `LPCTSTR`... Which is... a piece of sh*t.
Again: It's 2017. There's no reason using the ANSI version if the UNICODE version exists.

**Comment by mqudsi** [comment]
> Using the general name lstrlen doesn't make sense in this case.

I have `_UNICODE` defined now, so `lstrlen` is automatically defined as `lstrlenW`, and I'm passing in an `L` prefixed string so it should be fine.

**Comment by CarterLi** [comment]
The macro `_UNICODE` and `_MBCS` macros are not supposed to be defined in user code. General functions ( macro again...) are not defined to accept wide strings; they are defined to accept general strings. As you can see, `lstrlen` accepts LPCTSTR, which means `const TCHAR *`, not `const wchar_t *` nor `const char *`. It's not a matter of writing; it's a matter of meaning.
Just a suggestion: Use UNICODE version directly if you pass wide strings. They should be used together.

**Comment by FrankHB** [comment]
As a general suggestion, do not rely on encoding conversion based on Win32 API, including extension of CRT built on them. All of those are in a mess even more serious than `_T` craps. They are error-prone due to lack of guidance in documentation to tell programmers how to deal with it correctly, otherwise they would cause subtle compatibility problems. They may simply not work reliably in userland with standard tools distributed by Windows, and the codepage of UTF-8 is not a (well-tested) first-class citizen under Win32 (e.g. a plain `chcp 65001` could just crash in some `powershell` shipped with some versions of Windows). They may have dependencies on system locales (which is another source of the mess). They may have different behavior due to dependencies on particular versions of CRT. They may have performance penalties (even comparing to naively hand-rolled implementations). The true one stable way is to handle the conversion explicitly and then to interop using wide character version of console (Win32) API directly, which has first-class support in NT. Still note, the console may behave unexpectedly involving complicated Unicode scripts.

If you definitely need `wchar_t` stuff, better stick on the standard library when it is available, for better chance of clearly reasoning, clearer dependency path and (hopefully) better portability. For example, please use `std::char_traits<wchar_t>::length` or `std::wcslen` instead of `::lstrlenW` in your pure userland code. Nevertheless, `lstrlen` is plain wrong in sense of API usage because it relies on additional assumptions of implementation details which are not guaranteed to work.

**Comment by mqudsi** [comment]
@CarterLi  They're not defined in user code. It's the project settings. That's how they're meant to be used. I agree, if `_UNICODE` is set, `TCHAR` should normally be used, meaning `_T("")` instead of `L""`, but like you said - it's 2017, who uses ANSI anwyay?

**Comment by mqudsi** [comment]
@FrankHB I don't think we're relying on encoding conversion at this point. Unicode (as UTF-16) is read from the clipboard and written to the console. Can you explain what you mean by `lstrlen` being incorrect? It is, as used, typedef'd to `lstrlenW`, which expects (and is provided) a UTF-16-encoded string (stored in `wchar_t`).

**Comment by FrankHB** [comment]
Because `lstrlen` is not designed with expectation to be used like that as an interface. Being replaced by `lstrlenW` can not be deduced from occurrence of `lstrlen` solely, by missing contextual information about `_UNICODE` and the definition of the macro `lstrlen` (which is the implementation details), so the use of `lstrlen` is locally logically unsound. It is reasonable for code analysis to treat such use as an error. The suggestion can be either to use `TCHAR` and `lstrlen` together (with assumption of `_UNICODE` is defined), or to use `wchar_t` and `lstrlenW` together. (Nevertheless, both combinations are not worthwhile to use.)
